'use client';
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ur' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    about: 'About',
    menu: 'Menu',
    gallery: 'Gallery',
    reviews: 'Reviews',
    contact: 'Contact',
    orderNow: 'Order Now',
    exploreMenu: 'Explore Menu',
    addToCart: 'Add to Cart',
    checkout: 'Checkout',
    cart: 'Your Cart',
    total: 'Total',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    grandTotal: 'Grand Total',
    emptyCart: 'Your cart is empty',
    emptyCartSub: 'Add some delicious items to get started!',
    placeOrder: 'Place Order',
    success: 'Order Placed Successfully!',
    whyChooseUs: 'Why Choose Us',
    featured: 'Featured Dishes',
    account: 'Account',
    profile: 'Profile',
    myOrders: 'My Orders',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    settings: 'Settings',
    addresses: 'Addresses',
    name: 'Full Name',
    phone: 'Phone Number',
    email: 'Email Address',
    address: 'Delivery Address',
    notes: 'Order Notes',
    orderSummary: 'Order Summary',
    customerInfo: 'Customer Information',
    continueShopping: 'Continue Shopping',
    viewOrders: 'View Orders',
    reorder: 'Reorder',
    trackOrder: 'Track Order',
    backToOrders: 'Back to Orders',
    orderPlaced: 'Order Placed',
    orderConfirmed: 'Order Confirmed',
    preparing: 'Preparing',
    outForDelivery: 'Out for Delivery',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    totalOrders: 'Total Orders',
    activeOrders: 'Active Orders',
    completedOrders: 'Completed Orders',
    totalSpent: 'Total Spent',
    welcomeBack: 'Welcome back',
    noOrders: "You haven't placed an order yet",
    noOrdersSub: 'Browse our menu and place your first order!',
    noAddresses: 'No saved addresses yet',
    noAddressesSub: 'Add an address to speed up checkout',
    addAddress: 'Add Address',
    saveProfile: 'Save Profile',
    saveAddress: 'Save Address',
    deleteAddress: 'Delete Address',
    setDefault: 'Set as Default',
    home_label: 'Home',
    work_label: 'Work',
    other_label: 'Other',
    defaultAddress: 'Default',
    search: 'Search menu...',
    allCategories: 'All',
    itemsInCart: 'items in cart',
    addedToCart: 'Added to cart!',
    removedFromCart: 'Removed from cart',
    cartCleared: 'Cart cleared',
    orderSuccess: 'Order placed successfully!',
    profileUpdated: 'Profile updated!',
    addressSaved: 'Address saved!',
    reorderSuccess: 'Items added to cart!',
    languageChanged: 'Language changed',
    confirmRemove: 'Remove Item?',
    confirmRemoveMsg: 'will be removed from your cart.',
    confirmClearCart: 'Clear Cart?',
    confirmClearCartMsg: 'All items will be removed from your cart.',
    remove: 'Remove',
    cancel: 'Cancel',
    clear: 'Clear',
    required: 'This field is required',
    invalidPhone: 'Please enter a valid phone number',
    errorForm: 'Please fill in all required fields',
    estimatedDelivery: 'Estimated Delivery',
    orderDate: 'Order Date',
    deliveryInfo: 'Delivery Information',
    paymentSummary: 'Payment Summary',
    orderStatus: 'Order Status',
    items: 'Items',
    latestOrder: 'Latest Order',
    viewAll: 'View All',
    browseMenu: 'Browse Menu',
    language: 'Language',
    languageName: 'English',
  },
  ur: {
    home: 'ہوم',
    about: 'ہمارے بارے میں',
    menu: 'مینو',
    gallery: 'گیلری',
    reviews: 'تبصرے',
    contact: 'رابطہ',
    orderNow: 'آرڈر کریں',
    exploreMenu: 'مینو دیکھیں',
    addToCart: 'کارٹ میں شامل کریں',
    checkout: 'چیک آؤٹ',
    cart: 'آپ کا کارٹ',
    total: 'کل',
    subtotal: 'ذیلی کل',
    deliveryFee: 'ڈیلیوری فیس',
    grandTotal: 'مجموعی کل',
    emptyCart: 'آپ کا کارٹ خالی ہے',
    emptyCartSub: 'کچھ لذیذ چیزیں شامل کریں!',
    placeOrder: 'آرڈر پلیس کریں',
    success: 'آرڈر کامیابی سے ہو گیا!',
    whyChooseUs: 'ہمیں کیوں چنیں',
    featured: 'خاص ڈشز',
    account: 'اکاؤنٹ',
    profile: 'پروفائل',
    myOrders: 'میرے آرڈر',
    signIn: 'سائن ان',
    signOut: 'سائن آؤٹ',
    settings: 'ترتیبات',
    addresses: 'پتے',
    name: 'پورا نام',
    phone: 'فون نمبر',
    email: 'ای میل',
    address: 'ڈیلیوری پتہ',
    notes: 'آرڈر نوٹس',
    orderSummary: 'آرڈر خلاصہ',
    customerInfo: 'گاہک کی معلومات',
    continueShopping: 'خریداری جاری رکھیں',
    viewOrders: 'آرڈر دیکھیں',
    reorder: 'دوبارہ آرڈر',
    trackOrder: 'آرڈر ٹریک کریں',
    backToOrders: 'آرڈرز پر واپس',
    orderPlaced: 'آرڈر ہو گیا',
    orderConfirmed: 'آرڈر تصدیق ہو گئی',
    preparing: 'تیاری جاری ہے',
    outForDelivery: 'ڈیلیوری کے لیے روانہ',
    delivered: 'پہنچا دیا گیا',
    cancelled: 'منسوخ',
    totalOrders: 'کل آرڈر',
    activeOrders: 'فعال آرڈر',
    completedOrders: 'مکمل آرڈر',
    totalSpent: 'کل خرچ',
    welcomeBack: 'خوش آمدید',
    noOrders: 'ابھی تک کوئی آرڈر نہیں',
    noOrdersSub: 'ہمارا مینو دیکھیں اور پہلا آرڈر دیں!',
    noAddresses: 'ابھی تک کوئی پتہ محفوظ نہیں',
    noAddressesSub: 'چیک آؤٹ تیز کرنے کے لیے پتہ شامل کریں',
    addAddress: 'پتہ شامل کریں',
    saveProfile: 'پروفائل محفوظ کریں',
    saveAddress: 'پتہ محفوظ کریں',
    deleteAddress: 'پتہ حذف کریں',
    setDefault: 'ڈیفالٹ بنائیں',
    home_label: 'گھر',
    work_label: 'دفتر',
    other_label: 'دیگر',
    defaultAddress: 'ڈیفالٹ',
    search: 'مینو تلاش کریں...',
    allCategories: 'سب',
    itemsInCart: 'اشیاء کارٹ میں',
    addedToCart: 'کارٹ میں شامل!',
    removedFromCart: 'کارٹ سے ہٹا دیا',
    cartCleared: 'کارٹ صاف ہو گیا',
    orderSuccess: 'آرڈر کامیابی سے ہو گیا!',
    profileUpdated: 'پروفائل اپڈیٹ ہو گئی!',
    addressSaved: 'پتہ محفوظ ہو گیا!',
    reorderSuccess: 'اشیاء کارٹ میں شامل!',
    languageChanged: 'زبان تبدیل ہو گئی',
    confirmRemove: 'آئٹم ہٹائیں؟',
    confirmRemoveMsg: 'کو آپ کے کارٹ سے ہٹا دیا جائے گا۔',
    confirmClearCart: 'کارٹ صاف کریں؟',
    confirmClearCartMsg: 'تمام اشیاء کو کارٹ سے ہٹا دیا جائے گا۔',
    remove: 'ہٹائیں',
    cancel: 'منسوخ',
    clear: 'صاف کریں',
    required: 'یہ فیلڈ ضروری ہے',
    invalidPhone: 'درست فون نمبر درج کریں',
    errorForm: 'تمام ضروری فیلڈز پُر کریں',
    estimatedDelivery: 'متوقع ڈیلیوری',
    orderDate: 'آرڈر کی تاریخ',
    deliveryInfo: 'ڈیلیوری کی معلومات',
    paymentSummary: 'ادائیگی خلاصہ',
    orderStatus: 'آرڈر کی صورتحال',
    items: 'اشیاء',
    latestOrder: 'آخری آرڈر',
    viewAll: 'سب دیکھیں',
    browseMenu: 'مینو دیکھیں',
    language: 'زبان',
    languageName: 'اردو',
  },
  ru: {
    home: 'Home',
    about: 'Hamare Baare Mein',
    menu: 'Menu',
    gallery: 'Gallery',
    reviews: 'Reviews',
    contact: 'Rabta',
    orderNow: 'Order Karein',
    exploreMenu: 'Menu Dekhein',
    addToCart: 'Cart Me Dalein',
    checkout: 'Checkout',
    cart: 'Aapka Cart',
    total: 'Total',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    grandTotal: 'Grand Total',
    emptyCart: 'Aapka cart khali hai',
    emptyCartSub: 'Kuch mazedaar cheezein shamil karein!',
    placeOrder: 'Order Place Karein',
    success: 'Order Kamyabi Se Ho Gaya!',
    whyChooseUs: 'Humein Kyun Chunein',
    featured: 'Khas Dishes',
    account: 'Account',
    profile: 'Profile',
    myOrders: 'Mere Orders',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    settings: 'Settings',
    addresses: 'Patay',
    name: 'Pura Naam',
    phone: 'Phone Number',
    email: 'Email',
    address: 'Delivery Pata',
    notes: 'Order Notes',
    orderSummary: 'Order Summary',
    customerInfo: 'Customer Ki Maloomat',
    continueShopping: 'Shopping Jaari Rakhein',
    viewOrders: 'Orders Dekhein',
    reorder: 'Dobara Order',
    trackOrder: 'Order Track Karein',
    backToOrders: 'Orders Par Wapis',
    orderPlaced: 'Order Ho Gaya',
    orderConfirmed: 'Order Confirm Ho Gaya',
    preparing: 'Tayyari Jaari Hai',
    outForDelivery: 'Delivery Ke Liye Rawan',
    delivered: 'Pohncha Diya Gaya',
    cancelled: 'Mansookh',
    totalOrders: 'Kul Orders',
    activeOrders: 'Active Orders',
    completedOrders: 'Mukammal Orders',
    totalSpent: 'Kul Kharch',
    welcomeBack: 'Khush Aamdeed',
    noOrders: 'Abhi Tak Koi Order Nahi',
    noOrdersSub: 'Hamara menu dekhein aur pehla order dein!',
    noAddresses: 'Abhi Tak Koi Pata Nahi',
    noAddressesSub: 'Checkout tez karne ke liye pata shamil karein',
    addAddress: 'Pata Shamil Karein',
    saveProfile: 'Profile Save Karein',
    saveAddress: 'Pata Save Karein',
    deleteAddress: 'Pata Hatayein',
    setDefault: 'Default Banayein',
    home_label: 'Ghar',
    work_label: 'Daftar',
    other_label: 'Doosra',
    defaultAddress: 'Default',
    search: 'Menu talash karein...',
    allCategories: 'Sab',
    itemsInCart: 'items cart mein',
    addedToCart: 'Cart mein shamil!',
    removedFromCart: 'Cart se hata diya',
    cartCleared: 'Cart saaf ho gaya',
    orderSuccess: 'Order kamyabi se ho gaya!',
    profileUpdated: 'Profile update ho gayi!',
    addressSaved: 'Pata save ho gaya!',
    reorderSuccess: 'Items cart mein shamil!',
    languageChanged: 'Zaban tabdeel ho gayi',
    confirmRemove: 'Item Hatayein?',
    confirmRemoveMsg: 'ko aapke cart se hata diya jaega.',
    confirmClearCart: 'Cart Saaf Karein?',
    confirmClearCartMsg: 'Tamam items cart se hata diye jaenge.',
    remove: 'Hatayein',
    cancel: 'Mansookh',
    clear: 'Saaf Karein',
    required: 'Yeh field zaroori hai',
    invalidPhone: 'Durust phone number darj karein',
    errorForm: 'Tamam zaroori fields purr karein',
    estimatedDelivery: 'Mutawaqqa Delivery',
    orderDate: 'Order Ki Tarikh',
    deliveryInfo: 'Delivery Ki Maloomat',
    paymentSummary: 'Payment Summary',
    orderStatus: 'Order Ki Soorat',
    items: 'Items',
    latestOrder: 'Akhri Order',
    viewAll: 'Sab Dekhein',
    browseMenu: 'Menu Dekhein',
    language: 'Zaban',
    languageName: 'Roman Urdu',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['en', 'ur', 'ru'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => translations[language][key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
